name: market_news_app
description: My Market News App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  drift: ^2.20.3
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_dotenv: ^5.1.0
  fluttertoast: ^8.0.8
  fpdart: ^1.1.0
  freezed: ^2.4.5
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  onesignal_flutter: ^5.1.2
  meta: ^1.12.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  provider: ^6.1.2
  validators2: ^5.0.0
  timeago: ^3.6.1
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  loading_icon_button: ^0.0.7
  rxdart: ^0.28.0
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.1


dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  build_verify: ^3.1.0
  drift_dev: ^2.20.3
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.1
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  get_it: ^8.0.0
  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/app-logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
    google_fonts: true


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/env/

